### ISSUE TITLE
Need to update for v223

### ISSUE THREAD

**Issue by mindyourlifeguide** [alexey-anufriev/scopes-manager-intellij-plugin#11]
Need to update
![image](https://user-images.githubusercontent.com/35348648/205233021-0e8f3444-ed86-4ff3-af75-21f4c85f492e.png)
![image](https://user-images.githubusercontent.com/35348648/205233079-c721e12c-7a4f-474d-abae-21034a277c6d.png)

**Comment by alexey-anufriev** [comment]
hi @mindyourlifeguide,

Thank you for reporting this, I have also noticed this problem yesterday, after the upgrade.
I will publish a new version of the plugin in the next couple of days.
