### ISSUE TITLE
View changes when adding item to scope

### ISSUE THREAD

**Issue by cookieseller** [alexey-anufriev/scopes-manager-intellij-plugin#18]
Steps to reproduce:
1. Create a new scope and add some items
2. Switch to the newly created scope
3. Add a new item while being in the scope
4. Items are added but the view changes back to the project view and does not stay within the scope

Ideally I would like to stay in whatever view was open when adding a new scope item.

**Comment by cookieseller** [comment]
Sure, thing. So what you are describing works perfectly fine for me aswell, what I mean is something a bit different.
I want to add new files to an existing scope, while I have that scope open in the project view. 

So what happens is that I create a new scope which I will be working on for some time like "Currently Working".
I will always have that scope open and not leave it. When I do a drill down on a function which points to a different file, I may choose to add that to the scope. If I do that the project view will switch back to the "Project scope" (not sure what its called) instead of staying within "Currently Working".

![image](https://user-images.githubusercontent.com/1388823/227970416-49e6aaf4-1fcc-489d-bf1e-c2d3f070064a.png)
My "scope" list would look like this and I would like to stay within the one which was open when I added the file to a scope.

I hope that makes it a bit more clear, if not I can also provide a short clip of what I mean.

**Comment by cookieseller** [comment]
Sure thing, here is a short clip. You can see how the "project view" on the left side always jumps back to the complete file tree instead of keeping the scope selected.


https://user-images.githubusercontent.com/1388823/227991106-146d221c-1847-4912-ace3-aab45e2d1e65.mov

**Comment by alexey-anufriev** [comment]
Now I understood, you are using shortcuts to add a file. Thank you for the explanation. Now I will work on this issue.

**Comment by alexey-anufriev** [comment]
The fix will be released soon in 1.9.6.

**Comment by alexey-anufriev** [comment]
Release is available of the marketplace. I am closing this issue. Reopen/record a new one if the fix did not help.
