### ISSUE TITLE
Plugin broken in IntelliJ 2023.3.2

### ISSUE THREAD

**Issue by kwalker-foreflight** [alexey-anufriev/scopes-manager-intellij-plugin#19]
Great plugin, but it seems to be broken in the latest IntelliJ.

**Comment by alexey-anufriev** [comment]
@kwalker-foreflight, thank you for reporting, I will take a look asap.

**Comment by alexey-anufriev** [comment]
The new version is available - 1.9.5. Feel free to check it.

**Comment by bob-obringer** [comment]
Thank you @alexey-anufriev !

**Comment by kwalker-foreflight** [comment]
The features I regularly use are working again now, so I think this did it. Thanks for the cool plugin!

**Comment by kwalker-foreflight** [comment]
The features I regularly use are working again now, so I think this did it. Thanks for the cool plugin!
