### ISSUE TITLE
Rider - "Add to Scope" and "Remove from Scope" popup menus say  "Nothing here" even though scopes are available

### ISSUE THREAD

**Issue by trackroute** [alexey-anufriev/scopes-manager-intellij-plugin#20]
Firstly, thanks for the great plugin.

I'm trying to use the plugin with Rider (version 2023.3.2) on Linux, but it doesn't seem to be working correctly because the "Alt-S" and "Alt-D" popup menus say "Nothing here" even though there are both local and shared scopes configured. 

![Addtoscope](https://github.com/alexey-anufriev/scopes-manager-intellij-plugin/assets/28932050/a9e1c6ec-65c2-46aa-aabb-be1b12a69ae3)

Also, there are no "Add to Scope" and "Remove from Scope" and "Clear Scope" options in the right click menu (when right clicking on a file or folder).

![RightClickMenu](https://github.com/alexey-anufriev/scopes-manager-intellij-plugin/assets/28932050/ad24b680-7d39-4aae-88f2-c69bf272c5cf)

Note that this is a Rider specific problem. (The plugin is working perfectly with RustRover on my system).

Thanks.

**Comment by alexey-anufriev** [comment]
hi @trackroute, thank you for your contribution, I will take a look at this problem shortly.

**Comment by AAZANOVICH** [comment]
I Have the same issue, but just with "Remove from scope". 
When I click on module and press Opt + D (MacOS) I see "Nothing here", but when I select directory/package/file under module root, then I can see Scopes and remove selected directory/package/file (Not Entire module).

NOTE: Initially entire module was added to scope not separate files or directories etc.

**Comment by alexey-anufriev** [comment]
The fix will be released soon in 1.9.6.

**Comment by alexey-anufriev** [comment]
Release is available of the marketplace. I am closing this issue. Reopen/record a new one if the fix did not help.

**Comment by AAZANOVICH** [comment]
Updated to 1.9.6, same issue, nothing changed. Tried to uninstall plugin and install again and restart, doesn't help.

**Comment by alexey-anufriev** [comment]
@AAZANOVICH, could you please send me a screenshot?

**Comment by AAZANOVICH** [comment]
@alexey-anufriev Please see attached video.
Steps to reproduce:
1) Create Go project 1 (go-project-1)
2) Create Go project 2 (go-project-2)
3) From go-project-1 window add go-project-2 as a new module from source (File/New/Module From Existing Sources...)
4) Click on go-project-1 and use plugin shortcut to Create New Scope (Scope 1)
5) Click on go-project-2 and use plugin shortcut to Add  go-project-2 to previously created Scope 1
6) Click on go-project-2 and use plugin shortcut to delete go-project-2 from Scope 1

Expected:
Context menu should have Scope 1 listed
Actual:
Scope 1 is missed

Note: It works if go-project-1 is selected, seems like it works only for "parent project" which imported other modules.


https://github.com/alexey-anufriev/scopes-manager-intellij-plugin/assets/7366271/21bd802b-ab98-4523-aa4c-a5cdba0f8a98

**Comment by alexey-anufriev** [comment]
Should be fixed in 1.9.8.
