### ISSUE TITLE
Interact with Task "contexts"

### ISSUE THREAD

**Issue by RobFreundlich** [alexey-anufriev/scopes-manager-intellij-plugin#3]
I often work within an implicit scope defined by the "context" of the Issue/Task I'm working on. I don't know why IntelliJ calls it a context instead of a scope, or if they are different things under the covers, but the way it works is that when I switch from Task A to Task B, the files that are currently open are all closed, and the files that were open last time I worked on Task B are all opened. It's a nice feature.

The catch is that sometimes I'll have too many files open, and so I'll tell IntelliJ to close unmodified files. That clears the clutter, but might close files that I want opened for reference. So I have to remember what they were and open them again.

What would be great is if your plugin could interact with this "context". Ideally, the context would just appear in the list of scopes when I select "add to scope" - the scope's name could be the Task name. But if that's not possible, then maybe have "Create scope from open files", which would let me create and initialize a scope at any time, and then just use it like any other scope.

**Comment by alexey-anufriev** [comment]
@RobFreundlich, just to understand better, are you using this feature https://www.jetbrains.com/help/idea/managing-tasks-and-context.html? Or it is some other plugin?

**Comment by RobFreundlich** [comment]
Yup, @alexey-anufriev ,  that's the one I'm using.

**Comment by alexey-anufriev** [comment]
@RobFreundlich, one more question, just for me to understand better the use case. So you would switch from one context (task) to another, which has a lot of files open, then you select relevant files, add them to a scope named with a task name and then close all irrelevant files, but using scope you can filter the source tree and see all of them for reference at any time.

Is that approximately correct?

**Comment by RobFreundlich** [comment]
@alexey-anufriev yes, that sounds right.

**Comment by alexey-anufriev** [comment]
I have extended "Add to Scope" menu with 2 types of items.
1. "Create New.." -> will open a dialog suggesting to the user to create a new scope based on the selected resources
2. "Create New for Task ###" -> this will turn into one item per available task available in the Task Manager, so if you have two tasks "Some Work" and "Some Other Work" then you will get two more menu items "Create New for Task Some Work" and "Create New for Task Some Other Work".

These changes are available in v1.1.0. I have just submitted it for a review in the marketplace. It must be available in a couple of days.

@RobFreundlich, hope you gonna like it.

**Comment by alexey-anufriev** [comment]
@RobFreundlich, be available already ;)

**Comment by alexey-anufriev** [comment]
@RobFreundlich, I did a small improvement here, excluded completed tasks, so now the list of candidates must be cleaner.
You can get it in v1.1.1, it is in review now, hope soon will be released.

**Comment by RobFreundlich** [comment]
Thanks, @alexey-anufriev . I've got it, and will play around with it over the next couple of days as I work on various tasks.

**Comment by RobFreundlich** [comment]
OK, first impression: nice! But I have a few usability suggestions (of course!)

1. When getting the list of tasks, can you use the same query as the task list, instead of just getting all open tasks? That way, the tasks will show up in the same order, and the task I'm working on is more likely to be near the top of the list.
1. Can you provide a new option, "Create New from current task", at the top of the list?
1. When creating a new scope, can you add an option to include all currently open files?
1. Is there a way to track opening files? If so, could you add an option to "add files as they are opened"?

Thanks for your work on this, @alexey-anufriev !

**Comment by RobFreundlich** [comment]
Whoops - didn't mean to close this, meant to add a comment. I hate that the buttons are so close together!

Anyway, Found (and filed) a bug involved new scope for task and Default Task.

**Comment by alexey-anufriev** [comment]
Items 1, 2, and 3 have been included in v1.2.0.
The version is waiting for approval now, so soon you will be able to try these functionalities.

**Comment by RobFreundlich** [comment]
Awesome! I just got a notice about an update to v1.1.1, and am eagerly awaiting 1.2.0!

**Comment by alexey-anufriev** [comment]
@RobFreundlich, hope you had time to try new version of the plugin.
Can we close this issues then?

**Comment by RobFreundlich** [comment]
Yup. Looks great!
