### ISSUE TITLE
Weird interaction between "New scope for Task" and "Default Task:

### ISSUE THREAD

**Issue by RobFreundlich** [alexey-anufriev/scopes-manager-intellij-plugin#5]
Steps to reproduce it:

1. Make sure that you have the Tasks Dropdown in your toolbar
1. Tasks Dropdown -> Default Task --> DoubleClick (or whatever you want, to make it active)
1. Select a file
    1. Add to Scope --> Create New for Task A
    1. Observe that the Tasks Dropdown now displays Task A. **This is a bug**
1. Open the Tasks Dropdown
    1. Observe that the list no longer includes Default Task. **This is a bug**
1. Select Task A in the list and make it active
    1. Open the Tasks Dropdown
    1. Observe that the list now includes Default Task.
1. Select Default Task and make it active
    1. Observe that once again, the dropdown is showing as Task A instead of Default Task, and that if you open the Dropdown, Default Task is missing.

It appears that creating a scope for Task A while the Default Task is current has maybe overwritten the Default Task's name as "Task A"?

You'll also notice that if you add files to either the "Default Task/Task A" or the "Task A", they are available in the other scope. So the scopes system is seeing them as the same. The big problem for me here is that I often switch over to the Default Task when I want to temporarily clear things out to quickly check on a bug someone has asked me about, without impacting my current task work. With this bug, I can't do that.

**Comment by RobFreundlich** [comment]
This seems to be broader than I initially thought. I just went through the same steps, but starting from Task B instead of Default Task (that is, in step 2 above, choose Task B as your task instead of Default Task), and saw similar results - it looked like Task A was "overwriting" Task B.

I'm also noticing that the Run Configurations dropdown isn't updating to show the currently selected Run Configuration. So perhaps the problem here is that something is more generally interfering with dropdowns in the toolbar. I'm running IJntelliJ 2020.2.2 at this point.

**Comment by alexey-anufriev** [comment]
@RobFreundlich, thank you for the detailed test case, but unfortunately I couldn't reproduce it locally. Could you please try the following just to be sure that this is related to the plugin functionality rather than some IntelliJ problem. It looks like the top bar was just not refreshing for some reason, but I am not sure.

Anyway, first I would suggest you to reinstall the plugin and reproduce the steps again.

**Comment by RobFreundlich** [comment]
Some experimentation ...
### No Scopes Manager
I uninstalled Scopes Manager and did the following:
1. Go to Default Task
    1. Close all files
1. Go to Task A
    1. Open file Foo
1. Go to Default Task
    1. Observe that the toolbar shows Default Task **Good**
    1. Observe that Foo has closed **Good**
1. Go to Task A
    1. Observe that the toolbar shows Task A **Good**
    1. Observe that Foo is open **Good**
1. Go back to Default Task
    1. Observe that everything is correct again **Good**

### Reinstall Scopes Manager

1. Repeat the above steps, without adding files to scopes.
    1. Everything shows up correctly **Good**
1. While in Default Task, select file Bar (but don't open it)
    1. Add to Scope --> Create New for Task A
    1. Observe that the Tasks Dropdown still displays Default Task **Good** (and a change from my original report)
1. Go to Task A
    1. Observe that the toolbar displays Task A **Good**
    1. Observe that Foo is open **Good**
    1. Observe that Bar is not open **OK** Question: should it be open? Scopes Manager added it to a Scope, but is that the same as the Task Context?
1. Go to Default Task
    1. Observe that everything is as it should be **Good**
1. In the Project Panel, select Task A in the dropdown
    1. See only Foo and Bar **Good**

So yeah, it looks like things are working OK, and my original problem was an IntelliJ hiccup. Great! Other than the question I asked above, I think we're done here :-)

**Comment by alexey-anufriev** [comment]
@RobFreundlich in fact scopes and task contexts are different entities, that is why even if you add a file to the scope IDE does not add it to the context. 

The area where scopes are useful is rather project tree filtering:
![image](https://user-images.githubusercontent.com/932500/93774283-5d709100-fc21-11ea-9a05-ffc68f240795.png)

So the main idea behind the scopes is to have persistent contexts, whereas task contexts are rather live (tracking the user behavior).

**Comment by RobFreundlich** [comment]
Got it. Seems like a mistake on their part - the two concepts are so similar, there ought to be a way to automatically connect them. Your plugin is filling that gap pretty well :-)

As I mentioned over in [a comment on my other issue](https://github.com/alexey-anufriev/scopes-manager-intellij-plugin/issues/3#issuecomment-694882573), it'd be great to be able to add files to a specific scope as they are opened. That would fully tie the two together. The use case is that I sometimes want to go back and look at the files I worked on for a specific task. Sure, I can just open up that task, but having it as a scope feels more convenient.

But regardless, this bug is definitely done.

**Comment by alexey-anufriev** [comment]
I completely understand your point of view. I just have some unclear parts regarding this concept.
As all the scopes are kinda 'active' simultaneously there must be a way to define 'super-active' one that will be doing the tracking of open files. But we can start another issue in the tracker to discuss the possible solution.
